# Numpy
Numerical Python

In [1]:
import numpy as np

### ndarrays

In [4]:
data1= [6, 7.5, 8, 0, 1]
data1*2

[6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1]

In [6]:
arr1 = np.array(data1)
arr1*2

array([ 12.,  15.,  16.,   0.,   2.])

In [7]:
# Nested sequences will be converted into a multidimensional array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [12]:
arr2= np.array(data2)
arr2, arr2.ndim, arr2.shape

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), 2, (2, 4))

#### Creating new arrays
zeros, ones, empty, arange

In [13]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.empty((2,3,1))

array([[[ 0.],
        [ 0.],
        [ 0.]],

       [[ 0.],
        [ 0.],
        [ 0.]]])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### cast arrays
astype

In [19]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [21]:
float_arr =  arr.astype(np.float64)
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [24]:
numeric_strings = np.array(['1.23', '32.', '2.32'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.23,  32.  ,   2.32])

In [28]:
#we can also use another's dtype attribute
float_arr.astype(arr.dtype)

array([1, 2, 3, 4, 5])

### Operations between arrays

In [31]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [34]:
arr*arr + arr

array([[  2.,   6.,  12.],
       [ 20.,  30.,  42.]])

In [33]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

### Basic Indexing and Slicing

In [35]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5], arr[5:8]

(5, array([5, 6, 7]))

In [38]:
arr[5:8]= 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [40]:
# The data is not copied, and any modifications to the view will be 
# reflected in the source array

arr_slice = arr[5:8]
arr_slice[1] = 12345 

In [41]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [44]:
arr_slice[:] = 64

In [45]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

 If you want a copy of a slice of an ndarray :  
 
     arr[5:8].copy()

#### higher dimensional arrays

In [49]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr3d[1, 0]

array([7, 8, 9])

#### Indexing with slices

In [52]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [63]:
arr3d[:,1]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [64]:
arr3d[:, 1] = 0

In [65]:
arr3d

array([[[1, 2, 3],
        [0, 0, 0]],

       [[7, 8, 9],
        [0, 0, 0]]])

### Boolean Indexing

In [67]:
names = np.array(['Bob', 'Jose', 'Will', 'Jose', 'Jose', 'Bob', 'Will'])

In [84]:
data = np.random.randn(7, 4)
data

array([[-0.91776589,  1.81318656, -0.69701235,  0.4609818 ],
       [ 1.17533039,  0.65752213, -0.42729355, -0.30506766],
       [ 0.54956114, -0.10768298,  1.3608634 ,  0.55986477],
       [ 2.37112426,  0.10273777, -0.2538347 ,  0.33108211],
       [ 1.40843937, -2.02787102,  1.03815263,  1.68914553],
       [ 0.54469567,  0.75296059, -0.78659548, -1.22232052],
       [-1.7454679 ,  1.01084493,  0.42538005, -0.37146686]])

In [85]:
names == 'Bob'

array([ True, False, False, False, False,  True, False], dtype=bool)

In [86]:
# Selecting data from an array by boolean indexing always creates a copy of the data

data[names == 'Bob', 2:]

array([[-0.69701235,  0.4609818 ],
       [-0.78659548, -1.22232052]])

In [87]:
# Boolean arithmetic operands &(and), |(or)
# The keywords and, or do not work

mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[-0.91776589,  1.81318656, -0.69701235,  0.4609818 ],
       [ 0.54956114, -0.10768298,  1.3608634 ,  0.55986477],
       [ 0.54469567,  0.75296059, -0.78659548, -1.22232052],
       [-1.7454679 ,  1.01084493,  0.42538005, -0.37146686]])

In [89]:
# Setting values with boolean arrays works in a common-sense way

data[data < 0] = 0
data

array([[ 0.        ,  1.81318656,  0.        ,  0.4609818 ],
       [ 1.17533039,  0.65752213,  0.        ,  0.        ],
       [ 0.54956114,  0.        ,  1.3608634 ,  0.55986477],
       [ 2.37112426,  0.10273777,  0.        ,  0.33108211],
       [ 1.40843937,  0.        ,  1.03815263,  1.68914553],
       [ 0.54469567,  0.75296059,  0.        ,  0.        ],
       [ 0.        ,  1.01084493,  0.42538005,  0.        ]])

In [90]:
data[names != 'Jose'] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 1.17533039,  0.65752213,  0.        ,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 2.37112426,  0.10273777,  0.        ,  0.33108211],
       [ 1.40843937,  0.        ,  1.03815263,  1.68914553],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ]])

### Fancy Indexing
always copies the data into a new array

In [93]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i]= i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [96]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

##### reshape

In [99]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [100]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [105]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

##### np.ix_
converts two 1D integer arrays to an indexer that selects the square region

In [106]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])