# Pandas

In [2]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

## Series
one dimensional array-like object containing an array
of data and an associated array of data labels, called its index.

(a fixed-length, ordered dict)

In [4]:
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.values, obj.index

(array([ 4,  7, -5,  3]), RangeIndex(start=0, stop=4, step=1))

In [9]:
# to attach an index

obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [20]:
obj2[['a']] #Object

a   -5
dtype: int64

In [21]:
obj2['a']   #value correspondinf to index 'a'

-5

In [23]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [25]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [26]:
'b' in obj2

True

### Create Series from a Dict

In [31]:
sdata = {'Ohio': 3500, 'Texas': 7100, 'Utah':5000}

In [37]:
obj3 = Series(sdata)
obj3

Ohio     3500
Texas    7100
Utah     5000
dtype: int64

In [52]:
# with different index

states = ['NY', 'Utah', 'Texas']
obj4 = Series(sdata, index=states)
obj4

NY          NaN
Utah     5000.0
Texas    7100.0
dtype: float64

### .isnull(), .notnull()

In [53]:
obj4.isnull()

NY        True
Utah     False
Texas    False
dtype: bool

## Arithmetic operations

In [54]:
obj3 + obj4

NY           NaN
Ohio         NaN
Texas    14200.0
Utah     10000.0
dtype: float64

In [55]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
NY          NaN
Utah     5000.0
Texas    7100.0
Name: population, dtype: float64

In [56]:
obj4.index = ['a','b','c']
obj4

a       NaN
b    5000.0
c    7100.0
Name: population, dtype: float64

## DataFrame
a tabular spreadsheet-like data structure containing an ordered
collection of columns.

In [57]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
           'year': [2000, 2001, 2002, 2001, 2002],
           'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [58]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [60]:
# specify the columns order 

DataFrame(data, columns= ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [64]:
frame2 = DataFrame(data, columns= ['year', 'state', 'pop', 'debt'], 
                          index =['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [69]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [78]:
# Select colums

frame2['state'][:3]

one      Ohio
two      Ohio
three    Ohio
Name: state, dtype: object

In [79]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

### .ix
indexing field

In [84]:
# Select rows

frame2.ix['five']

year       2002
state    Nevada
pop         2.9
debt        NaN
Name: five, dtype: object

In [86]:
frame2.debt = np.arange(5)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [87]:
# Assign values using Series

val = Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
frame2.debt = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [103]:
# if the columns doesn't exist, it'll be created

frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

### del column

In [104]:
del frame2['eastern']

In [105]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

## Nested dict of dicts 

In [17]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 
          'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [18]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [118]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [121]:
DataFrame(pop, index =[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

## Dicts of Series

In [125]:
pdata = {'Ohio': frame3['Ohio'][:-1],
            'Nevada': frame3['Nevada'][:1]}
pdata

{'Nevada': 2000   NaN
 Name: Nevada, dtype: float64, 'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64}

In [127]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     NaN   1.7

In [128]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [129]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [131]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [133]:
#columns of different types

frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

## Index Objects

In [3]:
obj = Series(range(3), index =['a', 'b', 'c'])
index = obj.index

In [5]:
# Index objects are immutable

index

Index(['a', 'b', 'c'], dtype='object')

In [13]:
index = pd.Index(np.arange(3))
index

Int64Index([0, 1, 2], dtype='int64')

In [14]:
obj2 = Series([1.4, 2.3, 0], index=index)

In [15]:
obj2.index is index

True

In [19]:
# an Index als functions as a fixed-size set

frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [20]:
'Ohio' in frame3.columns

True

In [21]:
2003 in frame3.index

False

# Essential Functionality

### reindex
arranges the data according to the new index, introducing missing values

In [22]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [25]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

### method (ffill)
interpolation

In [27]:
# It may be desirable to do some interpolation of filling of values when reindexing

obj3 = Series(['blue', 'purple', 'yellow'], index= [0, 2, 4])

In [29]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [30]:
# reindex can alter either the (row) index, columsn or both

frame = DataFrame(np.arange(9).reshape(3, 3), index= ['a', 'b', 'd'],
                     columns= ['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
d     6      7           8

In [32]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   NaN    NaN         NaN
d   6.0    7.0         8.0

In [37]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
d      7   NaN           8

In [40]:
frame.reindex(index =['a', 'b', 'c', 'd'], method='ffill', columns= states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      4   NaN           5
d      7   NaN           8

### ix
indexing field

In [41]:
frame.ix[['a', 'b', 'c', 'd'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    4.0   NaN         5.0
c    NaN   NaN         NaN
d    7.0   NaN         8.0

## Droping entries from an axis

### drop

In [42]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [44]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [45]:
data = DataFrame(np.arange(16).reshape(4, 4), 
                    index =['Ohio', 'Colorado', 'Utah', 'NY'],
                    columns =['one', 'two', 'three', 'four'])

In [46]:
data.drop(['Colorado', 'Utah'])

one  two  three  four
Ohio    0    1      2     3
NY     12   13     14    15

In [48]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
NY         12     14    15

In [49]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
NY         12     14

## Indexing, selection and filtering
works analogously to NumPy

In [50]:
obj = Series(np.arange(4), index=['a', 'b', 'c', 'd'])

In [53]:
obj['b']

1

In [54]:
obj[2:4]

c    2
d    3
dtype: int64

In [55]:
obj[[1, 3]]

b    1
d    3
dtype: int64

In [57]:
obj[obj > 2]

d    3
dtype: int64

In [58]:
obj['b':'c']

b    1
c    2
dtype: int64

In [59]:
obj['b':'c'] = 5
obj

a    0
b    5
c    5
d    3
dtype: int64

In [60]:
data = DataFrame(np.arange(16).reshape(4, 4), 
                    index =['Ohio', 'Colorado', 'Utah', 'NY'],
                    columns =['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NY         12   13     14    15

In [61]:
data['two']

Ohio         1
Colorado     5
Utah         9
NY          13
Name: two, dtype: int64

In [62]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
NY           14   12

In [63]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [64]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
NY         12   13     14    15

In [65]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
NY        False  False  False  False

### .ix
indexing field

In [66]:
data.ix['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [67]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [68]:
data.ix[data.three >  5, :3]

one  two  three
Colorado    4    5      6
Utah        8    9     10
NY         12   13     14

## Arithmetic

In [8]:
s1 = Series([4., 2., 4., 9.], index = ['a', 'c', 'd', 'e'])
s2 = Series([-2.3, 3.2, 3.2, 0.4, 1], index = ['a', 'c', 'e', 'f', 'g'])

In [10]:
s1 + s2

a     1.7
c     5.2
d     NaN
e    12.2
f     NaN
g     NaN
dtype: float64

In [15]:
# In the case of DataFrame

df1 = DataFrame(np.arange(9).reshape(3, 3), columns= list('abc'),
                   index =['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12).reshape(4, 3), columns=list('bde'), 
                   index= ['Utah', 'Ohio', 'Texas', 'Orego'])

In [16]:
df1

a  b  c
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [17]:
df2

b   d   e
Utah   0   1   2
Ohio   3   4   5
Texas  6   7   8
Orego  9  10  11

In [18]:
df1 + df2

a     b   c   d   e
Colorado NaN   NaN NaN NaN NaN
Ohio     NaN   4.0 NaN NaN NaN
Orego    NaN   NaN NaN NaN NaN
Texas    NaN  10.0 NaN NaN NaN
Utah     NaN   NaN NaN NaN NaN

### fill_value

In [22]:
df1 = DataFrame(np.arange(12).reshape(3, 4), columns= list('abcd'))
df2 = DataFrame(np.arange(20).reshape(4, 5), columns= list('abcde')) 

In [23]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [24]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [26]:
# when reindexing

df1.reindex(columns = df2.columns)

a  b   c   d   e
0  0  1   2   3 NaN
1  4  5   6   7 NaN
2  8  9  10  11 NaN

In [27]:
df1.reindex(columns = df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

## Operations between DataFrame and Series

### broadcasting

In [28]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [35]:
frame = DataFrame(np.arange(12).reshape(4, 3), columns =list('bde'),
                     index =['Utah', 'Ohio', 'Texas', 'Orego'])
frame

b   d   e
Utah   0   1   2
Ohio   3   4   5
Texas  6   7   8
Orego  9  10  11

In [34]:
series = frame.ix[0]
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [36]:
frame - series

b  d  e
Utah   0  0  0
Ohio   3  3  3
Texas  6  6  6
Orego  9  9  9

In [39]:
# If you want to broadcast over the colums

series3 = frame['d']
series3

Utah      1
Ohio      4
Texas     7
Orego    10
Name: d, dtype: int64

In [40]:
frame.sub(series3, axis= 0)

b  d  e
Utah  -1  0  1
Ohio  -1  0  1
Texas -1  0  1
Orego -1  0  1

b   d   e
Utah   0   1   2
Ohio   3   4   5
Texas  6   7   8
Orego  9  10  11

## Function application and mapping
Numpy functions work fine with pandas object

In [43]:
frame = DataFrame(np.random.randn(4, 3), columns =list('bde'),
                     index =['Utah', 'Ohio', 'Texas', 'Orego'])
frame

b         d         e
Utah  -1.702298 -0.729468  0.696094
Ohio   0.782241 -1.547337 -0.573393
Texas  1.238066  0.317191 -1.200809
Orego -0.756588  2.512817  0.663570

In [44]:
np.abs(frame)

b         d         e
Utah   1.702298  0.729468  0.696094
Ohio   0.782241  1.547337  0.573393
Texas  1.238066  0.317191  1.200809
Orego  0.756588  2.512817  0.663570

In [48]:
f= lambda x: x.max() - x.min()

### apply method

In [52]:
frame.apply(f)

b    2.940364
d    4.060153
e    1.896903
dtype: float64

In [53]:
frame.apply(f, axis=1)

Utah     2.398391
Ohio     2.329578
Texas    2.438875
Orego    3.269405
dtype: float64

In [54]:
def f(x):
    return Series([x.min(), x.max()], index = ['min', 'max'])

In [55]:
frame.apply(f)

b         d         e
min -1.702298 -1.547337 -1.200809
max  1.238066  2.512817  0.696094

### applymap
element-wise

In [56]:
format = lambda x: '%.2f' % x

In [59]:
frame.applymap(format)

b      d      e
Utah   -1.70  -0.73   0.70
Ohio    0.78  -1.55  -0.57
Texas   1.24   0.32  -1.20
Orego  -0.76   2.51   0.66

In [60]:
frame['e'].map(format)

Utah      0.70
Ohio     -0.57
Texas    -1.20
Orego     0.66
Name: e, dtype: object

## Sorting and ranking

### sort_index method

In [61]:
obj = Series(range(4), index = ['d', 'a', 'b', 'c'])

In [62]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [63]:
frame = DataFrame(np.arange(8).reshape(2, 4), index=['three', 'one'],
                     columns= ['d', 'a', 'b', 'c'])

In [64]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [65]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [66]:
# Sortind in descending order

frame.sort_index(axis=1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

### order
sort_values

In [67]:
obj = Series([4, 7, -3, 2])

In [69]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [71]:
# When missing values are present

obj = Series([4, np.nan, 7, np.nan, -3, 2])

In [72]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [73]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [77]:
# to sort columns

frame.sort_values(by= 'b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [78]:
frame.sort_values(by = ['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

### rank method
ranking is closely realted to sorting: but it breaks ties by assigning each group the mean rank

In [79]:
obj = Series([7, -5, 7, 4, 2, 0, 4])

In [80]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [83]:
# according to the order they're observed in the data

obj.rank(method= 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [84]:
# in descending order

obj.rank( ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [85]:
frame = DataFrame({'b': [4.3, 4, -3, 2], 'a': [0, 1, 0, 1], 
                      'c': [-2, 5, 8, -2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  4.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [87]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  2.0  3.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

## Axis indexes with duplicate values

In [89]:
obj = Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [90]:
obj.index.is_unique

False

In [91]:
obj['a']

a    0
a    1
dtype: int64

In [92]:
df = DataFrame(np.random.randn(4, 3) , index = ['a', 'a', 'b', 'b'])

In [94]:
df.ix['b']

0         1         2
b  0.890856 -0.241552  0.458379
b -0.325716  0.433833  0.195558