# Pandas

In [24]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

## Series
one dimensional array-like object containing an array
of data and an associated array of data labels, called its index.

(a fixed-length, ordered dict)

In [4]:
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.values, obj.index

(array([ 4,  7, -5,  3]), RangeIndex(start=0, stop=4, step=1))

In [9]:
# to attach an index

obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [20]:
obj2[['a']] #Object

a   -5
dtype: int64

In [21]:
obj2['a']   #value correspondinf to index 'a'

-5

In [23]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [25]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [26]:
'b' in obj2

True

#### Create Series from a Dict

In [31]:
sdata = {'Ohio': 3500, 'Texas': 7100, 'Utah':5000}

In [37]:
obj3 = Series(sdata)
obj3

Ohio     3500
Texas    7100
Utah     5000
dtype: int64

In [52]:
# with different index

states = ['NY', 'Utah', 'Texas']
obj4 = Series(sdata, index=states)
obj4

NY          NaN
Utah     5000.0
Texas    7100.0
dtype: float64

#### .isnull(), .notnull()

In [53]:
obj4.isnull()

NY        True
Utah     False
Texas    False
dtype: bool

#### Arithmetic operations

In [54]:
obj3 + obj4

NY           NaN
Ohio         NaN
Texas    14200.0
Utah     10000.0
dtype: float64

In [55]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
NY          NaN
Utah     5000.0
Texas    7100.0
Name: population, dtype: float64

In [56]:
obj4.index = ['a','b','c']
obj4

a       NaN
b    5000.0
c    7100.0
Name: population, dtype: float64

## DataFrame
a tabular spreadsheet-like data structure containing an ordered
collection of columns.

In [57]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
           'year': [2000, 2001, 2002, 2001, 2002],
           'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [58]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [60]:
# specify the columns order 

DataFrame(data, columns= ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [64]:
frame2 = DataFrame(data, columns= ['year', 'state', 'pop', 'debt'], 
                          index =['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [69]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [78]:
# Select colums

frame2['state'][:3]

one      Ohio
two      Ohio
three    Ohio
Name: state, dtype: object

In [79]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

### .ix

In [84]:
# Select rows

frame2.ix['five']

year       2002
state    Nevada
pop         2.9
debt        NaN
Name: five, dtype: object

In [86]:
frame2.debt = np.arange(5)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [87]:
# Assign values using Series

val = Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
frame2.debt = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [103]:
# if the columns doesn't exist, it'll be created

frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

#### del column

In [104]:
del frame2['eastern']

In [105]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

### Nested dict of dicts 

In [116]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 
          'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [117]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [118]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [121]:
DataFrame(pop, index =[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

### Dicts of Series

In [125]:
pdata = {'Ohio': frame3['Ohio'][:-1],
            'Nevada': frame3['Nevada'][:1]}
pdata

{'Nevada': 2000   NaN
 Name: Nevada, dtype: float64, 'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64}

In [127]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     NaN   1.7

In [128]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [129]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [131]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [133]:
#columns of different types

frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)