# Gauss Elimination 

In [6]:

# Importing NumPy Library
import numpy as np
import sys

# Reading number of unknowns
n = int(input('Enter number of unknowns: '))

# Making numpy array of n x n+1 size and initializing 
# to zero for storing augmented matrix
a = np.zeros((n,n+1))

# Making numpy array of n size and initializing 
# to zero for storing solution vector
x = np.zeros(n)

# Reading augmented matrix coefficients
print('Enter Augmented Matrix Coefficients:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))

# Applying Gauss Elimination
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Divide by zero detected!')
        
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
        
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]

# Back Substitution
x[n-1] = a[n-1][n]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
    
    x[i] = x[i]/a[i][i]

# Displaying solution
print('\nRequired solution is: ')
for i in range(n):
    print('X%d = %0.3f' %(i,x[i]), end = '\t')


Enter number of unknowns: 3
Enter Augmented Matrix Coefficients:
a[0][0]=4
a[0][1]=1
a[0][2]=2
a[0][3]=4
a[1][0]=3
a[1][1]=5
a[1][2]=1
a[1][3]=7
a[2][0]=1
a[2][1]=1
a[2][2]=3
a[2][3]=3

Required solution is: 
X0 = 0.500	X1 = 1.000	X2 = 0.500	

In [8]:
a = [[4, 1, 2],[3, 5, 1],[1, 1, 3]] 
b = [4,7,3] 
#[0.5, 1.0, 0.5]

In [9]:
np.linalg.solve(a, b)

array([0.5, 1. , 0.5])

In [12]:
#https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html#scipy.linalg.solve
from scipy import linalg

x = linalg.solve(a, b)
x

array([0.5, 1. , 0.5])

# LU Decomposition 

In [34]:
# Decompose a matrix into lower and
# upper traingular matrix

def luDecomposition(mat, n):
 
    lower = [[0 for x in range(n)]
             for y in range(n)]
    upper = [[0 for x in range(n)]
             for y in range(n)]
 
    # Decomposing matrix into Upper
    # and Lower triangular matrix
    for i in range(n):
 
        # Upper Triangular
        for k in range(i, n):
 
            # Summation of L(i, j) * U(j, k)
            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])
 
            # Evaluating U(i, k)
            upper[i][k] = mat[i][k] - sum
 
        # Lower Triangular
        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1  # Diagonal as 1
            else:
 
                # Summation of L(k, j) * U(j, i)
                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])
 
                # Evaluating L(k, i)
                lower[k][i] = int((mat[k][i] - sum) /
                                  upper[i][i])
 
    # setw is for displaying nicely
    print("Lower Triangular\t\tUpper Triangular")
 
    # Displaying the result :
    for i in range(n):
 
        # Lower
        for j in range(n):
            print(lower[i][j], end="\t")
        print("", end="\t")
 
        # Upper
        for j in range(n):
            print(upper[i][j], end="\t")
        print("")


In [35]:
mat = [[2, -1, -2],
       [-4, 6, 3],
       [-4, -2, 8]]
 
luDecomposition(mat, 3)

Lower Triangular		Upper Triangular
1	0	0		2	-1	-2	
-2	1	0		0	4	-1	
-2	-1	1		0	0	3	


In [36]:
mat = [[1,1,0,3],[2,1,-2,1],[3,-1,-1,2],[-1,2,3,-1]]
#mat = [[1, 3, 5], [2, 4, 7], [1, 1, 0]]
luDecomposition(mat, 4)

Lower Triangular		Upper Triangular
1	0	0	0		1	1	0	3	
2	1	0	0		0	-1	-2	-5	
3	4	1	0		0	0	7	13	
-1	-3	0	1		0	0	0	-13	


In [38]:
# Decompose a matrix using Cholesky 
# Decomposition
import math

 
def Cholesky_Decomposition(matrix, n):
 
    lower = [[0 for x in range(n + 1)] 
                for y in range(n + 1)];
 
    # Decomposing a matrix
    # into Lower Triangular
    for i in range(n): 
        for j in range(i + 1): 
            sum1 = 0;
 
            # sum1mation for diagnols
            if (j == i): 
                for k in range(j):
                    sum1 += pow(lower[j][k], 2);
                lower[j][j] = float(math.sqrt(matrix[j][j] - sum1));
            else:
                 
                # Evaluating L(i, j)
                # using L(j, j)
                for k in range(j):
                    sum1 += (lower[i][k] *lower[j][k]);
                if(lower[j][j] > 0):
                    lower[i][j] = float((matrix[i][j] - sum1) /
                                               lower[j][j]);
 
    # Displaying Lower Triangular
    # and its Transpose
    print("Lower Triangular\t\tTranspose");
    for i in range(n): 
         
        # Lower Triangular
        for j in range(n):
            print(lower[i][j], end = "\t");
        print("", end = "\t");
         
        # Transpose of
        # Lower Triangular
        for j in range(n):
            print(lower[j][i], end = "\t");
        print("");

In [23]:
# Driver Code
n = 3;
matrix = [[4, 12, -16],
          [12, 37, -43],
          [-16, -43, 98]];
Cholesky_Decomposition(matrix, n);

Lower Triangular		Transpose
2.0	0	0		2.0	6.0	-8.0	
6.0	1.0	0		0	1.0	5.0	
-8.0	5.0	3.0		0	0	3.0	


In [44]:
n = 3;
matrix = [[4, -1, 1],
          [-1, 4.25, 2.75],
          [1, 2.75, 3.5]];
Cholesky_Decomposition(matrix, n)

Lower Triangular		Transpose
2.0	0	0		2.0	-0.5	0.5	
-0.5	2.0	0		0	2.0	1.5	
0.5	1.5	1.0		0	0	1.0	


In [41]:
from scipy.linalg import cholesky

L = cholesky(matrix, lower=True)
L

array([[ 2. ,  0. ,  0. ],
       [-0.5,  2. ,  0. ],
       [ 0.5,  1.5,  1. ]])

In [52]:
#the eigenvalues are exactly its diagonal entries
linalg.eig(L)

(array([1.+0.j, 2.+0.j, 2.+0.j]),
 array([[0.00000000e+00, 0.00000000e+00, 4.92672744e-16],
        [0.00000000e+00, 5.54700196e-01, 5.54700196e-01],
        [1.00000000e+00, 8.32050294e-01, 8.32050294e-01]]))

In [48]:
#The determinant equals the product of the diagonal entries
linalg.det(L)

4.0

In [66]:
# Log det

matrix = np.array([[4, -1, 1],
          [-1, 4.25, 2.75],
          [1, 2.75, 3.5]])

In [60]:
import scipy as sp

In [88]:
np.log(linalg.det(matrix))
#%timeit np.log(linalg.det(matrix))

2.772588722239781

In [86]:
np.log(cholesky(matrix).diagonal()).sum()*2.0
#%timeit np.log(cholesky(matrix).diagonal()).sum()*2.0

2.772588722239781

# Gauss Seidel

In [3]:
# Defining our function as seidel which takes 3 arguments 
# as A matrix, Solution and B matrix 
   
def seidel(a, x ,b): 
    #Finding length of a(3)        
    n = len(a)                    
    # for loop for 3 times as to calculate x, y , z 
    for j in range(0, n):         
        # temp variable d to store b[j] 
        d = b[j]                   
          
        # to calculate respective xi, yi, zi 
        for i in range(0, n):      
            if(j != i): 
                d-=a[j][i] * x[i] 
        # updating the value of our solution         
        x[j] = d / a[j][j] 
    # returning our updated solution            
    return x     

In [7]:
# int(input())input as number of variable to be solved                 
n = 3                              
a = []                             
b = []         
# initial solution depending on n(here n=3)                      
x = [0, 0, 0]                         
a = [[4, 1, 2],[3, 5, 1],[1, 1, 3]] 
b = [4,7,3] 
print(x) 
  
#loop run for m times depending on m the error value 
for i in range(0, 10):             
    x = seidel(a, x, b) 
    #print each time the updated solution 
    print(x) 

[0, 0, 0]
[1.0, 0.8, 0.39999999999999997]
[0.6000000000000001, 0.9599999999999997, 0.48000000000000004]
[0.52, 0.9919999999999998, 0.49600000000000005]
[0.504, 0.9983999999999998, 0.4992000000000001]
[0.5008, 0.99968, 0.49984]
[0.5001599999999999, 0.9999360000000002, 0.4999679999999999]
[0.500032, 0.9999872, 0.4999936]
[0.5000064, 0.9999974400000001, 0.49999871999999995]
[0.50000128, 0.999999488, 0.4999997439999999]
[0.500000256, 0.9999998976000001, 0.49999994880000004]


https://en.wikipedia.org/wiki/List_of_numerical_analysis_topics#Eigenvalue_algorithms